// <auto-generated />
namespace WFP_Aplikacja.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class m8 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m8));
        
        string IMigrationMetadata.Id
        {
            get { return "201911260007464_m8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
